Binary Matrix
big-data-lab-team/repro-tools pull request #36
Opened 2017-06-30 20:06 UTC by soudabeh19

(Option -b) Binary Matrix to represent the existence of difference in conditions pair according to the subject and file

2017-07-03 20:01 UTC, glatard requested changes
Nice work! Only minor changes are required, see inside comments.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +def n_differences_across_subjects(conditions_dict,root_dir,metrics,checksums_from_file_dict,checksum_after_file_path,check_corruption,sqlite_db_path,flag):
`flag` is not a good name for a parameter -> `return_detailed_differences`.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +    bDiff={}
A short comment would be appreciated.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +def n_differences_across_subjects(conditions_dict,root_dir,metrics,checksums_from_file_dict,checksum_after_file_path,check_corruption,sqlite_db_path,flag):
You should also document this in the function's comments.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +	    for file_name in path_names:
I don't think you need to loop twice over `path_names`.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +    if flag:
how about returning both anyways and removing the flag?

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +# an returns the stdout if and only if command was successful
there's a new typo here.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +#folder dictionairies as the value.
new typo here too.

2017-07-03 20:01 UTC, glatard commented on verifyFiles.py
> +            diff_file.write(pretty_string(Diff,conditions_dict))
don't capitalize variables (`Diff`).

2017-07-04 21:53 UTC, soudabeh19 commented on verifyFiles.py
> +def n_differences_across_subjects(conditions_dict,root_dir,metrics,checksums_from_file_dict,checksum_after_file_path,check_corruption,sqlite_db_path,flag):
sure

2017-07-04 21:54 UTC, soudabeh19 commented on verifyFiles.py
> +	    for file_name in path_names:
you are right

2017-07-04 21:55 UTC, soudabeh19 commented on verifyFiles.py
> +    bDiff={}
sure, I'll do

2017-07-04 21:56 UTC, soudabeh19 commented on verifyFiles.py
> +    if flag:
nice I'll do

2017-07-04 21:59 UTC, soudabeh19 commented on verifyFiles.py
> +# an returns the stdout if and only if command was successful
Thanks for your detailed review

2017-07-05 02:46 UTC, glatard requested changes
Just a small remaining comment.

2017-07-05 02:46 UTC, glatard commented on verifyFiles.py
> +def n_differences_across_subjects(conditions_dict,root_dir,metrics,checksums_from_file_dict,checksum_after_file_path,check_corruption,sqlite_db_path,return_detailed_differences):
You don't need the last parameter now that you always return both matrices.

2017-07-05 14:29 UTC, soudabeh19 commented on verifyFiles.py
> +def n_differences_across_subjects(conditions_dict,root_dir,metrics,checksums_from_file_dict,checksum_after_file_path,check_corruption,sqlite_db_path,return_detailed_differences):
Oops! totally right

2017-07-06 00:48 UTC, glatard commented
Hi @lalet, could you review this PR and make sure your stuff still works with these modifications?

2017-07-06 00:48 UTC, glatard approved these changes
Good to go! I'll just wait for @lalet's feedback before merging.

2017-07-06 15:23 UTC, lalet commented on verifyFiles.py
> +	parser.add_argument("-b","--binaryMatrix",help="Matrix showes diferences according to the subject and file in the comparision of condition pairs")
Could you please correct the typos in the help section of binaryMatix

2017-07-06 15:34 UTC, lalet requested changes
Good work @soudabeh19 !! 
I have requested for a few minor changes due to typos. 
If you have added a new parameter, I would recommend you to add it to the readme page as well.

2017-07-06 16:07 UTC, soudabeh19 commented on verifyFiles.py
> +	parser.add_argument("-b","--binaryMatrix",help="Matrix showes diferences according to the subject and file in the comparision of condition pairs")
Thanks for mentioning

2017-07-06 16:31 UTC, lalet approved these changes

2017-07-06 17:28 UTC, merged