Having a text file of binary-matrix
big-data-lab-team/repro-tools pull request #51
Opened 2017-10-04 17:32 UTC by soudabeh19

Adding text_files function to have :
row_index.txt
column_index.txt
matrix.txt

2017-10-05 15:20 UTC, glatard requested changes
See comments inline as discussed during meeting.

2017-10-05 15:20 UTC, glatard commented on verifyFiles.py
> +    print "\n\n  >>> Conditions order : ",bDiff.keys(), "\n" # letting know about order of values in binary matrix dataframe
keys in a dictionary are not ordered.

2017-10-05 15:20 UTC, glatard commented on verifyFiles.py
> +    tSpark={}
Remove if unused.

2017-10-05 15:20 UTC, glatard commented on verifyFiles.py
> +def text_files (bDiff,conditions_dict):
rename to "write_text_files"

2017-10-05 15:20 UTC, glatard commented on verifyFiles.py
> +    text_files (bDiff,conditions_dict)
Put this under the `-d` option, see https://github.com/big-data-lab-team/repro-tools/issues/52

2017-10-06 02:10 UTC, lalet commented
@soudabeh19 Tests are failing since there are changes in the parameters. Tests need to be edited.

2017-10-10 11:55 UTC, lalet approved these changes
Good work @soudabeh19 ! Approved. Minor changes are needed.

2017-10-10 11:55 UTC, lalet commented on verifyFiles.py
> +            log_info("Writes the difference matrices and indexs into files"+args.difference)
args.difference is the base name of the file. It would be better to edit the log info to a  more meaningful one.

2017-10-10 11:57 UTC, merged

2017-10-11 02:38 UTC, glatard commented on verifyFiles.py
> +	parser.add_argument("difference", help="Writes the difference matrices and indexs into files")
Help text should be "base name to use in output file names".