Modification in verifyFiles.py and  README.md
big-data-lab-team/repro-tools pull request #54
Opened 2017-10-11 15:11 UTC by soudabeh19

2017-10-11 16:13 UTC, lalet requested changes

2017-10-11 16:13 UTC, lalet commented on verifyFiles.py
> +            log_info("Writes the difference matrices and indexs into files")
Typo : Indexs = > Indexes

2017-10-12 14:53 UTC, glatard requested changes
Just improve the help message and rename the parameters.

2017-10-12 14:53 UTC, glatard commented on verifyFiles.py
> +	parser.add_argument("difference", help="Base name to use in output file names")
Rename parameter `result_base_name`. Explain in the help that the following files will be written: <result_base_name>_....txt (small explanation), etc.

2017-10-13 00:41 UTC, lalet commented
@soudabeh19 I guess you haven't made a pull from upstream.

2017-10-13 14:30 UTC, merged